Move from shurcooL/VFSgen to go embed.
ppc64le-cloud/kubetest2-plugins pull request #79
Opened 2022-11-29 10:07 UTC by kishen-v

Changes introduced:

1. Eliminates dependency from `"github.com/shurcooL/vfsgen"` by using `go embed` directive.
2. The ansible-submodule is now replaced with a git subtree, to enable embedding files into binary.
3. The README.md has been updated with the required content, to update the k8s-ansible subtree.
4. The files related to asset generation and the /hack/build.sh have been removed.
5. Assets for plugin have been moved from `kubetest2-plugins/data/data/*` to `kubetest2-plugins/data/*`

2022-11-29 10:09 UTC, kishen-v commented on data/unpack.go
> +		err := os.MkdirAll(extractPath, 0777)
Switched to using `os.MkdirAll`, to suppress error if path already exists.

2022-11-29 10:31 UTC, kishen-v commented
Job `pull-kubetest2-plugins-terraform-validate` had failed due to the changes in the asset's path. A supporting PR is raised - https://github.com/ppc64le-cloud/test-infra/pull/356.

2022-12-02 08:23 UTC, mkumatag requested changes
minor comments, overall lgtm

2022-12-02 08:23 UTC, mkumatag commented on data/unpack.go
>  			}
```suggestion
			if err := Unpack(filepath.Join(extractPath, name), filepath.Join(resPath, name)); err != nil {
				return err
			}
```

2022-12-02 09:32 UTC, kishen-v commented
Changes post : https://github.com/ppc64le-cloud/kubetest2-plugins/pull/80

1. Update `Makefile` to clone the `k8s-submodule`.
2. Update Readme.md.

2022-12-02 10:33 UTC, mkumatag commented
@Rajalakshmi-Girish Not sure why bot isn't merging, merging it manually.

2022-12-02 10:33 UTC, merged